spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6380
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
#server:
#  port: 8081
#
#app:
#  redis:
#    host: 127.0.0.1
#    port: 26379
#    database: 0
#    cluster:
#      password: 123123123
#      nodes:
#        - 127.0.0.1:6301
#        - 127.0.0.1:6302
#        - 127.0.0.1:6303
