spring:
#  data:
#    redis:
#      repositories:
#        enabled: true
        
  redis:    host: 192.168.0.219
    port: 6379
#    lettuce:#      pool:#        max-active: 10
#        max-idle: 10
#        min-idle: 2